
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yyntswapsjtksjqdvabf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5bnRzd2Fwc2p0a3NqcWR2YWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNTc3MjIsImV4cCI6MjA4ODczMzcyMn0.AFdqH8qZE8enI0yQAgPbkEXvkmMrgFIYFzULgI9mHOI";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
